// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorBufferContext } from "./EditorBufferContext";

export type BufferMessage = { requestId: string, bufferName: string, buffer: EditorBufferContext, };
