// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgb } from "./Rgb";

export type ColorRange = { range: [number, number], bgColor: Rgb | null, fgColor: Rgb | null, };
