// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorRange } from "./ColorRange";
import type { EditorCursorContext } from "./EditorCursorContext";
import type { EditorWindow } from "./EditorWindow";

export type EditorBufferContext = { cursors: Array<EditorCursorContext>, content: Array<string>, colors: Array<Array<ColorRange>>, memory: Array<string>, bufferWindow: EditorWindow, tabWidth: number, };
