// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BufferMessage } from "./BufferMessage";
import type { ContextMessage } from "./ContextMessage";
import type { InputMessage } from "./InputMessage";

export type ServerMessages = { "message_type": "context", "info": ContextMessage } | { "message_type": "input", "info": InputMessage } | { "message_type": "buffer", "info": BufferMessage };
